## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [1]:
import pandas as pd

In [2]:
# загружаем датасет
data = pd.read_csv(r"D:\Projects\de_courses\data\adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [57]:
# сделаем копию данных для дальнейшего анализа
df = data.copy(deep=True)
print(df['sex'].unique())

['Male' 'Female']

In [58]:
male_count = df[df['sex'] == 'Male'].shape[0]
female_count = df[df['sex'] == 'Female'].shape[0]

print("Количество мужчин: {}".format(male_count))
print("Количество женщин: {}".format(female_count))

Количество мужчин: 21790
Количество женщин: 10771

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [59]:
# Вычисляем среднее для столбца age
print("Средний возраст мужчин:")
male_average_age = df[df['sex'] == 'Male']['age'].mean()
print(round(male_average_age))

Средний возраст мужчин:
39

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [60]:
us_count = df[df['native-country'] == 'United-States'].shape[0]
percent_of_us_users = us_count / df.shape[0]
print("Доля граждан Соединенных Штатов: {:.2%}".format(percent_of_us_users))

Доля граждан Соединенных Штатов: 89.59%

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [61]:
less50_avg_age = df[df['salary'] == '<=50K']['age'].mean()
print("Среднее значение возраста тех, кто получает менее 50К в год: {}".format(round(less50_avg_age)))
more50_avg_age = df[df['salary'] == '>50K']['age'].mean()
print("Среднее значение возраста тех, кто получает более 50К в год: {}".format(round(more50_avg_age)))

less50_std_age = df[df['salary'] == '<=50K']['age'].std()
print("\nСреднеквадратичное отклонение возраста тех, кто получает менее 50К в год: {}".format(round(less50_std_age)))
more50_std_age = df[df['salary'] == '>50K']['age'].std()
print("Среднеквадратичное отклонение возраста тех, кто получает более 50К в год: {}".format(round(more50_std_age)))

Среднее значение возраста тех, кто получает менее 50К в год: 37
Среднее значение возраста тех, кто получает более 50К в год: 44

Среднеквадратичное отклонение возраста тех, кто получает менее 50К в год: 14
Среднеквадратичное отклонение возраста тех, кто получает более 50К в год: 11

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [63]:
print(df[df['salary'] == '>50K']['education'].unique())

['HS-grad' 'Masters' 'Bachelors' 'Some-college' 'Assoc-voc' 'Doctorate'
 'Prof-school' 'Assoc-acdm' '7th-8th' '12th' '10th' '11th' '9th' '5th-6th'
 '1st-4th']

Как видно из вывода, не все люди, которые получают больше 50К, имеют высшее образование.

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [68]:
new_df = df[['age', 'race', 'sex']]
group_stats = new_df.groupby(["race", "sex"]).describe()
print(group_stats['age']['max'])

race                sex
Amer-Indian-Eskimo  Female    80.0
                    Male      82.0
Asian-Pac-Islander  Female    75.0
                    Male      90.0
Black               Female    90.0
                    Male      90.0
Other               Female    74.0
                    Male      77.0
White               Female    90.0
                    Male      90.0
Name: max, dtype: float64

Максимальный возраст мужчин расы Asian-Pac-Islander = 90.

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [69]:
more50_df = df[(df['sex'] == 'Male') & (df['salary'] == '>50K')]

mask_married = more50_df[more50_df['marital-status'].str.contains('Married')]
print("Количество женатых мужчин, зарабатывающих много: {}".format(mask_married.shape[0]))

mask_not_married = more50_df[~more50_df['marital-status'].str.contains('Married')]
print("Количество неженатых мужчин, зарабатывающих много: {}".format(mask_not_married.shape[0]))

Количество женатых мужчин, зарабатывающих много: 5965
Количество неженатых мужчин, зарабатывающих много: 697

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [70]:
#сортируем данные по столбу 'hours-per-week' по убыванию
sorted_data = df.sort_values(by='hours-per-week', ascending=False)
#извлекаем первое (максимальное) значение столбца 'hours-per-week' (первоя строка, 13 столбец)
max_hours = sorted_data.iloc[0, 12] 
print("Максимальное число часов работы в неделю: {}".format(max_hours))

df_max_hours = df[df['hours-per-week'] == 99]
print("\nЛюдей, работающих максимальное число часов в неделю: {}".format(df_max_hours.shape[0]))

percent_of_rich_users = df_max_hours[df_max_hours['salary'] == '>50K'].shape[0] / df_max_hours.shape[0]
print("\nСреди них - процент людей, зарабатывающих много:  {:.2%}".format(percent_of_rich_users))

Максимальное число часов работы в неделю: 99

Людей, работающих максимальное число часов в неделю: 85

Среди них - процент людей, зарабатывающих много:  29.41%

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [71]:
avg_hours = df.groupby(['salary', 'native-country'])['hours-per-week'].mean()
avg_hours

salary  native-country
<=50K   ?                  40.164760
        Cambodia           41.416667
        Canada             37.914634
        China              37.381818
        Columbia           38.684211
                             ...
>50K    Thailand           58.333333
        Trinadad&Tobago    40.000000
        United-States      45.505369
        Vietnam            39.200000
        Yugoslavia         49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [72]:
# Создаём столбец с начальным значением
df['AgeGroup'] = 'default'

# Устанавливаем значения на основе условий
df.loc[(df['age'] >= 16) & (df['age'] <= 35), 'AgeGroup'] = 'young'
df.loc[(df['age'] > 35) & (df['age'] <= 70), 'AgeGroup'] = 'adult'
df.loc[(df['age'] > 70) & (df['age'] <= 100), 'AgeGroup'] = 'retiree'

df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [73]:
df_more50 = df[df['salary'] == '>50K']
count_more50 = df_more50.groupby('AgeGroup')['age'].count().reset_index()
print(count_more50)

  AgeGroup   age
0    adult  6042
1  retiree    94
2    young  1705

Возрастная группа, в которой чаще зарабатывают более 50К: adult.

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [74]:
grouped_occupation = df.groupby('occupation')[['age' ,'hours-per-week']].describe().reset_index()
grouped_occupation

           occupation     age                                                \
                        count       mean        std   min   25%   50%   75%
0                   ?  1843.0  40.882800  20.336350  17.0  21.0  35.0  61.0
1        Adm-clerical  3770.0  36.964456  13.362998  17.0  26.0  35.0  46.0
2        Armed-Forces     9.0  30.222222   8.089774  23.0  24.0  29.0  34.0
3        Craft-repair  4099.0  39.031471  11.606436  17.0  30.0  38.0  47.0
4     Exec-managerial  4066.0  42.169208  11.974548  17.0  33.0  41.0  50.0
5     Farming-fishing   994.0  41.211268  15.070283  17.0  29.0  39.0  52.0
6   Handlers-cleaners  1370.0  32.165693  12.372635  17.0  23.0  29.0  39.0
7   Machine-op-inspct  2002.0  37.715285  12.068266  17.0  28.0  36.0  46.0
8       Other-service  3295.0  34.949621  14.521508  17.0  22.0  32.0  45.0
9     Priv-house-serv   149.0  41.724832  18.633688  17.0  24.0  40.0  57.0
10     Prof-specialty  4140.0  40.517633  12.016676  17.0  31.0  40.0  48.0
11    Protective-serv   649.0  38.953775  12.822062  17.0  29.0  36.0  47.0
12              Sales  3650.0  37.353973  14.186352  17.0  25.0  35.0  47.0
13       Tech-support   928.0  37.022629  11.316594  17.0  28.0  36.0  44.0
14   Transport-moving  1597.0  40.197871  12.450792  17.0  30.0  39.0  49.0

         hours-per-week
     max          count       mean        std  min   25%   50%   75%   max
0   90.0         1843.0  31.906131  14.908311  1.0  20.0  36.0  40.0  99.0
1   90.0         3770.0  37.558355   9.589833  1.0  37.0  40.0  40.0  80.0
2   46.0            9.0  40.666667  14.071247  8.0  40.0  40.0  48.0  60.0
3   90.0         4099.0  42.304221   9.052038  1.0  40.0  40.0  45.0  99.0
4   90.0         4066.0  44.987703  11.109113  1.0  40.0  40.0  50.0  99.0
5   90.0          994.0  46.989940  17.320156  2.0  40.0  40.0  60.0  99.0
6   90.0         1370.0  37.947445  10.580459  2.0  36.0  40.0  40.0  95.0
7   90.0         2002.0  40.755744   7.592691  1.0  40.0  40.0  40.0  96.0
8   90.0         3295.0  34.701669  12.706004  1.0  25.0  40.0  40.0  99.0
9   81.0          149.0  32.885906  16.184548  4.0  22.0  35.0  40.0  99.0
10  90.0         4140.0  42.386715  12.536315  1.0  40.0  40.0  50.0  99.0
11  90.0          649.0  42.870570  12.331777  3.0  40.0  40.0  45.0  99.0
12  90.0         3650.0  40.781096  13.236410  2.0  35.0  40.0  50.0  99.0
13  73.0          928.0  39.432112  10.583093  3.0  40.0  40.0  40.0  99.0
14  90.0         1597.0  44.656230  12.721380  5.0  40.0  40.0  50.0  99.0

In [75]:
# создадим функцию, которая возвращает только те группы, которые удовлетворяют условию
def filter_func():
    # список только тех занятостей, у которых средний возраст людей не больше сорока
    groupd_mean_age = grouped_occupation[grouped_occupation['age']['mean'] <= 40]
    list_mean_age = groupd_mean_age.occupation.unique().tolist()
    
    # список только тех занятостей, у которых все работники отрабатывают более 5 часов в неделю
    # (значит минимальное значение для группы людей должно быть выше 5 часов)
    groupd_min_hours = grouped_occupation[grouped_occupation['hours-per-week']['min'] > 5]
    list_min_hours = groupd_min_hours.occupation.unique().tolist()
    
    # Находим совпадающие значения в двух списках
    common_occupations = [item for item in list_mean_age if item in list_min_hours]
    
    return common_occupations

In [76]:
list_occupations = filter_func()
list_occupations

['Armed-Forces']

In [77]:
result_df = df[df['occupation'].isin(list_occupations)]
result_df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
442,24,Federal-gov,191073,HS-grad,9,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,<=50K,young
1300,29,Federal-gov,301010,Some-college,10,Never-married,Armed-Forces,Not-in-family,Black,Male,0,0,60,United-States,<=50K,young
14613,39,Federal-gov,227597,HS-grad,9,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,50,United-States,<=50K,adult
16111,24,Federal-gov,287988,Bachelors,13,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,40,United-States,<=50K,young
18034,34,Federal-gov,172716,12th,8,Married-civ-spouse,Armed-Forces,Husband,White,Male,0,0,40,United-States,<=50K,young
18644,23,Federal-gov,163870,Some-college,10,Never-married,Armed-Forces,Other-relative,White,Male,0,0,40,United-States,<=50K,young
18769,30,Federal-gov,76313,HS-grad,9,Married-civ-spouse,Armed-Forces,Other-relative,Amer-Indian-Eskimo,Male,0,0,48,United-States,<=50K,young
25799,46,Federal-gov,344415,Masters,14,Married-civ-spouse,Armed-Forces,Husband,White,Male,0,1887,40,United-States,>50K,adult
32316,23,Federal-gov,173851,HS-grad,9,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,8,United-States,<=50K,young